### ISSUE TITLE
[Bug] When I hibernate my computer and reopen it, the app will crash

### ISSUE THREAD

**Issue by Xionghaizi001** [myfix16/BatteryTracker#71]
**Describe the bug**
When I use "hibernate" to power off my laptop instead of "shutdown", and the next time I resume my lap with battery NOT full, this app will crash by some unknown reason. But when I wait the battery charged to full, the app will running normally.

当我使用“休眠”代替“关机”来切断笔记本电源后，下次从“休眠”状态中恢复电脑，且电池未充满，软件会因为一些未知原因崩溃。但如果我等到电脑充满电再打开，软件就不会崩溃。

**To Reproduce**
1. Unplugged your laptop / 拔掉电脑电源
2. Make the battery not full (less than 80%) / 让电池电量低于80%
3. Hibernate your device / 休眠你的设备
4. Wait for a while (more than 2 or 3 hours) / 等待一段时间(大于2到3小时)
5. Reopen your device / 重新开机
6. The app will crash / Bug复现

**Expected behavior**
The app running normally.
 App正常运行。

**Screenshots**
Because it involves to power operation, I can't provide any screenshots.
因为这个Bug涉及到电源操作且时间跨度较大，我无法提供截图。

**Desktop (please complete the following information):**
 Windows 10 22H2 (10.0.19045.4529)

**Additional context**
None.

**Comment by myfix16** [comment]
Hi, can you attach your logs here? They can be found by clicking Settings > About > Open log folder. Thanks!

你好，你可以附上app的日志吗？日志文件可以在 设置>关于>打开日志文件夹 找到。谢谢！

**Comment by Xionghaizi001** [comment]
> Hi, can you attach your logs here? They can be found by clicking Settings > About > Open log folder. Thanks!
> 
> 你好，你可以附上app的日志吗？日志文件可以在 设置>关于>打开日志文件夹 找到。谢谢！

~Got it. When this bug happend again, I post it to you.~

I found some logs at the time _MAYBE_ it's crashed. I don't know when the app will record a log but it may recorded at the time which bug has happened inferred by my using behavior.

> 2024-05-28T11:05:09.6640750+08:00  [INF] Display on, register power events (7dae5858)
2024-05-28T11:05:18.4809393+08:00  [FTL] Unhandled exception (f80f533c)
System.InvalidOperationException: UpdateIcon failed.
   at H.NotifyIcon.Core.TrayIcon.UpdateIcon(IntPtr handle) in /_/src/libs/H.NotifyIcon/Core/TrayIcon.cs:line 468
   at ABI.Microsoft.UI.Xaml.PropertyChangedCallback.Do_Abi_Invoke(IntPtr thisPtr, IntPtr d, IntPtr e)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IDependencyObjectMethods.SetValue(IObjectReference _obj, DependencyProperty dp, Object value)
   at H.NotifyIcon.TaskbarIcon.<>c__DisplayClass163_0.<<OnIconSourceChanged>g__OnGeneratedIconSourceOnDependencyPropertyChanged|0>d.MoveNext() in /_/src/libs/H.NotifyIcon.Shared/TaskbarIcon.IconSource.cs:line 34
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
2024-05-28T22:32:39.6978282+08:00  [INF] App launched with activation kind: Launch (7e94bc79)
2024-05-28T22:32:43.0428666+08:00  [INF] App launched with command line args: [""] (ad1c8b1e)
2024-05-28T23:08:22.2061690+08:00  [INF] Display off, unregister power events (43442015)
2024-05-28T23:23:46.1936604+08:00  [INF] Display on, register power events (7dae5858)
2024-05-28T23:25:08.9412382+08:00  [INF] Display off, unregister power events (43442015)

**Comment by myfix16** [comment]
It looks like the crash has something to do with the tray icon library I use (H.NotifyIcon https://github.com/HavenDV/H.NotifyIcon). I will try to reproduce the problem on my computer and see if I can find the cause.
